import type { NextPage } from 'next';
import Head from 'next/head';
import { PostBox } from '../components/PostBox/PostBox';

const Home: NextPage = () => {
  return (
    <div className="max-w-5xl my-7 mx-auto">
      <Head>
        <title>GraphQL Reddit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex">
        <PostBox />
      </div>
    </div>
  );
};

export default Home;
