import type { NextPage } from 'next';
import Head from 'next/head';
import { Feed } from '../components/Feed/Feed';
import { PostBox } from '../components/PostBox/PostBox';

const Home: NextPage = () => {
  return (
    <div className="max-w-5xl my-7 mx-auto">
      <Head>
        <title>GraphQL Reddit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <PostBox />
      <div className="flex">
        <Feed />

        <div className="sticky top-36 mx-5 mt-5 hidden h-fit min-w-[300px] rounded-md border border-gray-300 lg:inline">
          <p>Top Communities</p>
          <div>{/* communities list */}</div>
        </div>
      </div>
    </div>
  );
};

export default Home;
